version: "3"

volumes:
  docker-volume:

services:
  # nginx
  web:
    container_name: nginx-app
    image: nginx:1.18
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - my_network

  # PHP
  app:
    container_name: php
    build: ./docker/php
    image: php:7.4-fpm
    volumes:
      - .:/var/www/html
      # ホストのエイリアスコマンドを共有
      - ~/.bashrc:/root/.bashrc
    depends_on:
      - db
      - redis
      - laravel_echo_server
    links:
      - db
      - redis
    networks:
      - my_network

  #Mysql
  db:
    container_name: db-host
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      TZ: 'Asia/Ho_Chi_Minh'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - docker-volume:/var/lib/mysql
    networks:
      - my_network

  # Redis server
  redis:
    image: redis:latest
    container_name: db-redis
    volumes:
      - docker-volume:/data
    networks:
      - my_network
    ports:
      - 6379:6379

  laravel_echo_server:
    build:
      context: ./docker/laravel-echo
      dockerfile: Dockerfile
    volumes:
      - ./laravel/.env:/app/.env
    networks:
      - my_network
    restart: unless-stopped
  # Phpmyadmin (optional)
#  phpmyadmin:
#    container_name: phpmyadmin
#    image: phpmyadmin/phpmyadmin
#    environment:
#    - PMA_ARBITRARY=1
#    - PMA_HOSTS=db
#    - PMA_USER=root
#    - PMA_PASSWORD=
#    ports:
#    - 8080:80
#    networks:
#      - my_network

networks:
  my_network:
    external: true
#    ipam:
#      config:
#        - subnet: 172.22.3.0/24